### ISSUE TITLE
Browser back button (history) doesn't work very well in Config Pages

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#504]
When navigating backward using the browser back button, it gets stuck to the current page even after clicking multiple times.

It needs more investigating to understand why.

PS: This seems to affect the configs page, other pages seems to work as expected.

**Comment by sagarrchauhan** [comment]
@mainawycliffe is this applicable for all the routes under /configs? I see this buggy behaviour only when the current route is /configs/changes. Or when going to that route from any other route. 
For /configs/changes, the issue is there is no pagination and there is a lot of data coming in to be processed. That is one of the reasons even for the page freeze.

**Comment by mainawycliffe** [comment]
@sagarrchauhan Sorry for the late reply. I also noticed it when I navigated from topology to a single config item, and the back button was very buggy as well.
