### ISSUE TITLE
Make severity tag case insensitive

### ISSUE THREAD

**Issue by Kaitou786** [flanksource/flanksource-ui#88]
When adding the `severity` label in the check it doesn't pick up it's severity if all small casing is used.
See:
![Screenshot 2021-12-23 at 4 30 15 PM](https://user-images.githubusercontent.com/36669272/147231215-c0eeaeea-eac4-4822-8ee4-701e4fb3d5d2.png)

It still shows up in the label filter but I think it should also be visible in the check modal

**Comment by johnflank** [comment]
@Kaitou786 I have already set it up so that it simply displays whatever string that's under `selectedCheck.severity`. It will only show `-` if the particular check's `severity` field is either empty or nullish. 

It seems that those groups of checks which, despite having the `severity: high` label, does not have anything under its `severity` field

![image](https://user-images.githubusercontent.com/88124024/147447231-8f77ffa6-049e-4637-b2be-866913169f09.png)

**Comment by Kaitou786** [comment]
Yeah I think we should support this functionality but not on the UI side but mutate the object if `severity` label is defined we can populate the spec.check.severity field if empty

**Comment by johnflank** [comment]
Yeah agreed. if there's no further issues about this on the UI side then I'll probably close this issue by tomorrow
