### ISSUE TITLE
In Settings -> Health, clicking on "Config Source" crashes the UI

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#967]
![image](https://user-images.githubusercontent.com/13419481/226567849-ae6de711-92bd-448f-bd6a-ae318037b49c.png)

The page goes blank & there's no error in console.

![image](https://user-images.githubusercontent.com/13419481/226567985-190f0de5-16e1-4d2a-8c57-e27ee1bdda94.png)

**Comment by gitstart** [comment]
@adityathebe @moshloop I would like to pick this up

**Comment by gitstart** [comment]
@adityathebe After doing some research, I need some clarifications because I think I found the cause of the bug.
When a user clicks the `Config source` the URL is updated and it tries to navigate to that source. say for example when we are on this route 
````
http://localhost:3000/settings/canaries/01874bec-a868-30f5-be8c-ed07364ef4e9
````
when the user clicks the button the source is `kubernetes/770f6dac-5f8a-4dac-9cb3-dacdd5bf81dc` it tries to navigate to it like this.
````
http://localhost:3000/settings/canaries/kubernetes/770f6dac-5f8a-4dac-9cb3-dacdd5bf81dc
````
But this route configuration doesn't exist, as seen below the `settings` route supports 2 sub-route that is the `list & details` pages of each resource

![Screenshot 2023-04-14 at 09 20 53](https://user-images.githubusercontent.com/50529081/231987192-ceef0583-6a61-4603-8423-bbc7400c2d23.png)

So my question is when the user clicks on `Config source` which page do they want to be rerouted to? Currently, it's not clear which.

Cc @moshloop
